spring:
  application:
    name: microservicesJuly2

  boot:
    admin:
      client:
        url: http://localhost:9090   # Admin Server URL

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"   # expose all actuator endpoints
  endpoint:
    health:
      show-details: always
